### ISSUE TITLE
ControllerManager doesn't check for new joysticks after initialization

### ISSUE THREAD

**Issue by james20902** [james20902/spiral#4]

**Comment by james20902** [comment]
Checks for controllers, but the robot program doesn't initialize until something is found and the controller not found message pops up every time even with controller plugged in initially.

**Comment by bluetangkid** [comment]
Should probably make a recurring task every 200-500ms to refresh the controller list, I can do that tomorrow because sleep time.

**Comment by james20902** [comment]
I was actually planning on using the new competitionExecution and standardExecution methods for tasks, where competitionExecution keeps checking for controllers and the moment one is found the array is resized to fit those controllers and it doesn't check for any more. standardExecution would fill the controller array with controller objects regardless of if something is plugged in or not.
